# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mnenonen <mnenonen@student.hive.fi>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/10/21 22:10:44 by mnenonen          #+#    #+#              #
#    Updated: 2019/10/21 22:12:35 by mnenonen         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	gcc ./srcs/main.c -o ft_display_file

clean:

fclean: clean
	rm ft_display_file
